name: education_platform
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  jwt_decoder: ^2.0.1  # JWT Token'ı decode etmek için
  carousel_slider: ^4.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets section to include the images
  assets:
    - assets/img/hero/  # This will include the "hero" folder under the "assets/img" directory

